name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.404 # Thay thế x bằng phiên bản cụ thể, ví dụ: 7.0.100

    - name: Build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o publish
      env:
        DOTNET_ROOT: ${{ steps.setup-dotnet.outputs.dotnet-path }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: voting  # Thay thế bằng tên ứng dụng của bạn trên Azure
        package: ${{ github.workspace }}/publish
        slot-name: production  # Thay thế bằng slot name nếu có

    
